app:
  port: 8081
  logging:
    development: true
    JsonOutputMode: true
  swagger.enabled: false
  minio:
    Endpoint: storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: I2TCgnjRBzblw6rP50sO
    SecretAccessKey: T9tKE6lCGDWBUnijwjt2V324tBa6x0joVSzza3OG
    UseSSL: true
    BucketName: voice-changer-dev
  files:
    BaseInputPath: "/root/app/audio"
    BaseOutputPath: "/root/app/audio"
    BaseModelPath: "/root/app/voice-changer-backend/assets/weights/rvc"
  rvc:
    Endpoint: http://localhost:8080
    InferPath: /api/v1/rvc/infer
  asynq:
    Addr: 194.233.85.239:6379
    Password: braly@123
    DB: 1
    Queues:
      vc_default: 10
    Worker:
      Concurrency: 10
