app:
  port: 8083
  logging:
    development: true
    JsonOutputMode: false
  swagger.enabled: false
  minio:
    Endpoint: dev.storage.bralyvn.com
    PublicEndpoint: https://dev.storage.bralyvn.com
    AccessKeyID: uCCpbIoWR4ddYi1I94MS
    SecretAccessKey: w3Ydr8YTSwJxtcl9H9NrTK8oI0EF4yR77VPY0zMu
    UseSSL: false
    BucketName: voice-changer
  files:
    BaseInputPath: "/home/liam/Downloads/voice-changer-backend"
    BaseOutputPath: "/home/liam/Downloads/voice-changer-backend"
    BaseModelPath: "/home/liam/Downloads/voice-changer-backend/models"
    ModelPaths:
      trump:
        model: "/trump/G_68800.pth"
        config: "/trump/config.json"
  svc:
    Endpoint: http://localhost:8082
    InferPath: /api/v1/infer

  uvr:
    Endpoint: http://localhost:8083
    InferPath: /api/v1/uvr/infer
  asynq:
    Addr: localhost:6379
    Password: braly@123
    DB: 1
    Queues:
      level_2: 20
      default: 10
    Worker:
      Concurrency: 10
