app:
  port: 8081
  logging:
    development: true
    JsonOutputMode: true
  swagger.enabled: false
  minio:
    Endpoint: storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: I2TCgnjRBzblw6rP50sO
    SecretAccessKey: T9tKE6lCGDWBUnijwjt2V324tBa6x0joVSzza3OG
    UseSSL: true
    BucketName: vca
  files:
    BaseInputPath: "/root/app/audio"
    BaseOutputPath: "/root/app/audio"
  rvc:
    Endpoint: http://localhost:8080
    InferPath: /api/v1/rvc/infer
  asynq:
    Addr: 94.72.114.19:6379
    Password: 2V324tBa6x0joVSzza3OG
    DB: 1
    Queues:
      vc_default: 10
    Worker:
      Concurrency: 15
