app:
  port: 8080
  tls:
    Enabled: true
    CertFile: "/home/ssl/fullchain.pem"
    KeyFile: "/home/ssl/privkey.pem"
  middlewares:
    AuthenticationEnabled: false
  firebase:
    CredentialsFileAndroid: "/home/ssl/vca-firebase-service-account.json"
    CredentialsFileIOS: "/home/ssl/vca-firebase-service-account.json"
  logging:
    development: true
  swagger.enabled: true
  minio:
    Endpoint: storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: I2TCgnjRBzblw6rP50sO
    SecretAccessKey: T9tKE6lCGDWBUnijwjt2V324tBa6x0joVSzza3OG
    UseSSL: true
    BucketName: vca
  asynq:
    Addr: 94.72.114.19:6379
    Password: 2V324tBa6x0joVSzza3OG
    DB: 1
