app:
  port: 8081
  logging:
    development: true
    JsonOutputMode: false
  swagger.enabled: true
  firebase.Enabled: false
  middlewares.AuthenticationEnabled: false
  minio:
    Endpoint: storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: I2TCgnjRBzblw6rP50sO
    SecretAccessKey: T9tKE6lCGDWBUnijwjt2V324tBa6x0joVSzza3OG
    UseSSL: true
    BucketName: voice-changer-dev
  asynq:
    Addr: localhost:6379
    Password: braly@123
    DB: 1
