app:
  port: 8080
  tls:
    Enabled: true
    CertFile: "/app/ssl/fullchain.pem"
    KeyFile: "/app/ssl/privkey.pem"
  middlewares:
    AuthenticationEnabled: true
  firebase:
    CredentialsFileAndroid: "/app/ssl/vca-firebase-prod-service-account.json"
    CredentialsFileIOS: "/app/ssl/vca-firebase-prod-service-account.json"
  logging:
    development: false
  swagger.enabled: true
  minio:
    Endpoint: storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: I2TCgnjRBzblw6rP50sO
    SecretAccessKey: T9tKE6lCGDWBUnijwjt2V324tBa6x0joVSzza3OG
    UseSSL: true
    BucketName: vca
  asynq:
    Addr: 10.0.0.2:6379
    Password: 2V324tBa6x0joVSzza3OG
    DB: 1
