definitions:
  resources.CreateInference:
    properties:
      deadline:
        description: Deadline for completing the task
        type: string
      id:
        type: string
      max_retry:
        type: integer
      model:
        type: string
      retention:
        description: Retention in hours for how long to store the task info
        type: string
      status:
        description: 'Status of the task. Values: active, pending, scheduled, retry,
          archived, completed'
        type: string
      task_id:
        description: '@Deprecated'
        type: string
      type:
        type: string
    type: object
  resources.Inference:
    properties:
      completed_at:
        type: string
      deadline:
        type: integer
      enqueued_at:
        type: string
      id:
        type: string
      last_err:
        type: string
      last_failed_at:
        type: integer
      max_retry:
        type: integer
      model:
        type: string
      queue:
        type: string
      retried:
        type: integer
      src_file_url:
        type: string
      status:
        description: 'Status of the task. Values: active, pending, scheduled, retry,
          archived, completed'
        type: string
      target_file_url:
        type: string
      task_id:
        description: '@Deprecated'
        type: string
      task_status:
        type: string
      transpose:
        type: integer
      type:
        type: string
    type: object
  resources.Model:
    properties:
      category:
        type: string
      id:
        type: string
      logo_url:
        type: string
      name:
        type: string
    type: object
  response.Meta:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      meta:
        $ref: '#/definitions/response.Meta'
    type: object
info:
  contact: {}
  title: Voice Changer API Public
  version: 1.0.0
paths:
  /api/v1/infer:
    post:
      consumes:
      - multipart/form-data
      operationId: create-inference
      parameters:
      - description: Source voice
        in: formData
        name: file
        required: true
        type: file
      - description: Target voice
        in: formData
        name: model
        required: true
        type: string
      - default: vc
        description: Task's type
        in: formData
        name: type
        required: true
        type: string
      - default: 0
        description: Transpose
        in: formData
        name: transpose
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/resources.CreateInference'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Change voice of an audio file to target voice
      tags:
      - InferenceController
  /api/v1/infer/{id}:
    get:
      consumes:
      - application/json
      operationId: get-inference
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/resources.Inference'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get status of an inference task
      tags:
      - InferenceController
  /api/v1/models:
    get:
      consumes:
      - application/json
      operationId: get-models
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/resources.Model'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get list supported models
      tags:
      - ModelController
swagger: "2.0"
